{{- range $key, $val := .Values.versions }}
{{- if $val.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}-html-{{ $val.versionLabel }}
data:
  index.html: {{ $val.htmlContent | quote }}
---
{{- end }}
{{- end }}
